[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

[invariant]
runs = 128
depth = 128

# We can set fail_on_revert to true to make the invariant fail if any transaction reverts.
# This is useful for testing that a contract is not vulnerable to reentrancy.
# Set this to false if you want to test a contract that reverts on purpose.
# Set this to true if you want to test a contract that should never revert.
fail_on_revert = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
